#!/usr/bin/env bash
# set the default editor to Vim
export EDITOR=vim
export VISUAL=vim

# ignore common large directories in grep
export GREP_OPTIONS='--exclude-dir=.svn --exclude-dir=.git --exclude-dir=tmp'

# set colors for LS; make directory names easier to read
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# don't save duplicates in bash history
export HISTCONTROL=ignoredups:erasedups

export FZF_DEFAULT_COMMAND='
  (git ls-files ||
   find . -path "*/\.*" -prune -o -type f -print -o -type l -print |
      sed s/^..//) 2> /dev/null'
